# Generated by Django 4.1.1 on 2022-10-13 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codegether', '0003_requirement_project_creator_project_requirements'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.RemoveField(
            model_name='project',
            name='requirements',
        ),
        migrations.AddField(
            model_name='project',
            name='requirements',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
