# Generated by Django 4.1.1 on 2022-10-15 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codegether', '0005_remove_project_collaborators_alter_project_creator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='requirements',
            field=models.TextField(blank=True),
        ),
        migrations.RemoveField(
            model_name='project',
            name='upvotes',
        ),
        migrations.AddField(
            model_name='project',
            name='upvotes',
            field=models.ManyToManyField(to='codegether.userprofile'),
        ),
    ]
