# Generated by Django 4.1.1 on 2022-10-16 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codegether', '0006_alter_project_requirements_remove_project_upvotes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='upvotes',
            field=models.ManyToManyField(blank=True, to='codegether.userprofile'),
        ),
    ]
