# Generated by Django 4.1.1 on 2022-10-22 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('codegether', '0007_alter_project_upvotes'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Requirement',
        ),
    ]
