# Generated by Django 4.1.1 on 2022-10-22 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codegether', '0009_project_slug_alter_project_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
