# Generated by Django 4.1.1 on 2022-10-23 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codegether', '0017_userprofile_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(null=True, upload_to='pfp'),
        ),
    ]
