# Generated by Django 4.1.1 on 2022-10-23 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('codegether', '0018_alter_userprofile_profile_picture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='profile_picture',
            new_name='pfp',
        ),
    ]
